### PR TITLE
Fix initialization for lastResetIdentitiesTs (resolves #58)

### LINKED ISSUE #58: Missing AnalyticsResponse on sessions first hits
Hi, we currently have warnings with missing AnalyticsResponses for our sessions first "Track State" Hits in Adobe Assurance.
While debugging into Adobe Analytics source code, I found that `timestamp` was equal to ` analyticsState.lastResetIdentitiesTimestampSec`.
Which happens quite a lot on early hits, as timestamps are recorded in seconds and not in milliseconds.

Problem: No AnalyticsResponse is send due to `timestamp > analyticsState.lastResetIdentitiesTimestampSec`.

Proposal: `timestamp >= analyticsState.lastResetIdentitiesTimestampSec`

See https://github.com/adobe/aepsdk-analytics-android/blob/066c980e58d673dca2e2344aee1c201172fe8f19/code/analytics/src/main/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessor.kt#L182

### PR DESCRIPTION
**Pull request by emdobrin**
## Description

lastResetIdentitiesTimestampSec should be initialized with 0 by default, and updated when resetIdentities events are processed. 
Previously it was set to current timestamp, preventing the analytics response event to be dispatched for track events sent on bootup.

## How Has This Been Tested?

Unit tests
Manual tests with test app and Assurance connection

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by cacheung — APPROVED** [review]

File: code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessorTests.kt [hunk 1]
```diff
@@ -385,4 +386,79 @@ class AnalyticsHitProcessorTests {
...
+            assertTrue(String(request.body).contains(payload))
+            countDownLatch.countDown()
+        }
+
+        assertEquals(0, analyticsHitProcessor.getLastHitTimestamp())
+
+        analyticsHitProcessor.processHit(dataEntity) {
+            assertTrue(it)
+            countDownLatch.countDown()
+        }
```
Comment (kevinlind) [inline code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessorTests.kt:452]: nit: name closure argument for readability
```
analyticsHitProcessor.processHit(dataEntity) { processingComplete ->
            assertTrue(processingComplete)
            countDownLatch.countDown()
        }
```

File: code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessorTests.kt [hunk 2]
```diff
@@ -385,4 +386,79 @@ class AnalyticsHitProcessorTests {
...
```
Comment (kevinlind) [inline code/analytics/src/test/java/com/adobe/marketing/mobile/analytics/internal/AnalyticsHitProcessorTests.kt:418]: nit: name closure argument for readability
```
analyticsHitProcessor.processHit(dataEntity) { processingComplete ->
            assertTrue(processingComplete)
            countDownLatch.countDown()
        }
```

**Review by kevinlind — APPROVED** [review]
